// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Balena.Entities.Common;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Balena.Entities.Models;

public partial class Category: AuditableEntity
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public string Image { get; set; }
    [NotMapped]
    public string OldFileName { get; set; }
    [NotMapped]
    public IFormFile Files { get; set; }
    public ICollection<Product> Products { get; set; } = new List<Product>();
}