// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Balena.Entities.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateOnly? JoinDate { get; set; }

    public ICollection<Order> Orders { get; set; } = new List<Order>();
}