// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Balena.Entities.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string FullName { get; set; }

    public string Role { get; set; }

    public string Phone { get; set; }

    public DateOnly? HireDate { get; set; }

    public decimal? Salary { get; set; }

    public ICollection<Order> Orders { get; set; } = new List<Order>();
}