// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Balena.Entities.Common;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace Balena.Entities.Models;

public partial class Product: AuditableEntity
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public int? CategoryId { get; set; }
    public decimal Price { get; set; }
    public string Description { get; set; }
    public string Image { get; set; }
    [NotMapped]
    public string CategoryName { get; set; }
    [NotMapped]
    public string OldFileName { get; set; }
    [NotMapped]
    public IFormFile Files { get; set; }
    public virtual Category Category { get; set; }
    public ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
    public ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
    public ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();
}