// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Balena.Entities.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string ContactName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public ICollection<Product> Products { get; set; } = new List<Product>();
}